# Generated by Django 4.2.23 on 2025-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entire_place", "ENTIRE_PLACE"),
                    ("private_room", "PRIVATE_ROOM"),
                    ("shared_room", "SHARED_ROOM"),
                ],
                max_length=20,
            ),
        ),
    ]
